// ============================================================
// DATA FILE — single source of truth
// ============================================================

export const pages = [
  // ─────────────────────────── GOKUL ──────────────────────────
  {
    id: "gokul",
    name: "Gokul",
    logoUrl: "assets/images/gokul.png",
    cardVariant: "variant-1",
    defaultLanguage: "english",
    imageFolder: "assets/images/gokulItems/",

    tabs: [
      { id: "5", label: "₹5 Items" },
      { id: "500g", label: "500g" },
      { id: "other", label: "Other" },
    ],

    items: [
      // ── ₹5 Items ──
      { id: 1, tabId: "5", name: "Masala cup", gujarati: "મસાલા કપ", price: 52, imageUrl: "Masala_Cup_Front-_image-500x500.png" },
      { id: 2, tabId: "5", name: "Tomato cup", gujarati: "ટમેટા કપ", price: 52, imageUrl: "Tomato_Cup_Front_image-500x500.png" },
      { id: 3, tabId: "5", name: "Plane", gujarati: "પ્લેન", price: 52, imageUrl: "Aeroplan_Front_image-500x500.png" },
      { id: 4, tabId: "5", name: "ABCD", gujarati: "એબીસીડી", price: 52, imageUrl: "Alphabet_Front_img-500x500.png" },
      { id: 5, tabId: "5", name: "Chowkadi", gujarati: "ચોકડી", price: 52, imageUrl: "Chowkadi_Front_image-500x500.png" },
      { id: 6, tabId: "5", name: "Plain ponga", gujarati: "પ્લેન પોંગા", price: 52, imageUrl: "Gokul-Ponga-Front-lq-500x500.png" },
      { id: 7, tabId: "5", name: "Wheels", gujarati: "વ્હીલ્સ", price: 52, imageUrl: "Wheels-FOP-500x500.png" },
      { id: 8, tabId: "5", name: "Pasta", gujarati: "પાસ્તા", price: 52, imageUrl: "Pasta-FOP-500x500.png" },
      { id: 9, tabId: "5", name: "Trayo", gujarati: "ત્રાયો", price: 52, imageUrl: "Trayo-FOP-500x500.png" },
      { id: 10, tabId: "5", name: "Raw Trayo", gujarati: "રૉ ત્રાયો", price: 52, imageUrl: "Raw_Trayo_Image-500x500.webp" },
      { id: 11, tabId: "5", name: "PopCorn", gujarati: "પોપકોર્ન", price: 52, imageUrl: "Popcorn_Final_FOP-500x500.webp" },
      { id: 12, tabId: "5", name: "Corn V Garlic Chilli", gujarati: "કોર્ન વી ગાર્લિક ચિલી", price: 52, imageUrl: "Gokul-Garlic-Chilli-Corn-V-Rs.5-Mockup-Pouch_Front-500x500.jpg" },
      { id: 13, tabId: "5", name: "Masala Corn V", gujarati: "મસાલા કોર્ન વી", price: 52, imageUrl: "Corn-Masala-FOP-500x500.webp" },
      { id: 14, tabId: "5", name: "Tomato Corn V", gujarati: "ટમેટા કોર્ન વી", price: 52, imageUrl: "Corn-Tomato-FOP-500x500.webp" },
      { id: 15, tabId: "5", name: "Bhavnagri gathiya", gujarati: "ભાવનગરી ગાંઠિયા", price: 51, imageUrl: "Bhavnagri-Gathiya-FOP-500x500.webp" },
      { id: 16, tabId: "5", name: "Nylon gathiya", gujarati: "નાયલોન ગાંઠિયા", price: 51, imageUrl: "NylonGathiya_FOP-500x500.webp" },
      { id: 17, tabId: "5", name: "Sev", gujarati: "સેવ", price: 51, imageUrl: "Sev_FOP-500x500.webp" },
      { id: 18, tabId: "5", name: "Papdi", gujarati: "પાપડી", price: 51, imageUrl: "PapdiGathiya_FOP-500x500.webp" },
      { id: 19, tabId: "5", name: "Tikha mitha mix", gujarati: "તીખા મીઠા મિક્સ", price: 51, imageUrl: "Tikha-Mitha-Mix-FOP-500x500.webp" },
      { id: 20, tabId: "5", name: "Dabela chana", gujarati: "દાબેલા ચણા", price: 51, imageUrl: "Dabela-Chana_FOP-500x500.png" },
      { id: 21, tabId: "5", name: "Chana dal", gujarati: "ચણા દાળ", price: 51, imageUrl: "Chana-Dal_FOP-500x500.png" },
      { id: 22, tabId: "5", name: "Sakkarpara", gujarati: "સક્કરપારા", price: 51, imageUrl: "Sakkarpara_FOP-500x500.webp" },
      { id: 23, tabId: "5", name: "Masala noodles", gujarati: "મસાલા નૂડલ્સ", price: 42.5, imageUrl: "MasalaNoodles-FOP-500x500.webp" },
      { id: 24, tabId: "5", name: "Masala wafers", gujarati: "મસાલા વેફર્સ", price: 52, imageUrl: "Masala-Wafer-FOP-500x500.webp" },
      { id: 25, tabId: "5", name: "Salty(Kesari) wafers", gujarati: "સોલ્ટી (કેસરી) વેફર્સ", price: 52, imageUrl: "Salty_FOP-500x500.webp" },
      { id: 26, tabId: "5", name: "Chilli wafers", gujarati: "ચિલી વેફર્સ", price: 52, imageUrl: "Hot-Chilli_FOP-500x500.png" },
      { id: 27, tabId: "5", name: "Creamy Onion", gujarati: "ક્રીમી ઓનિયન", price: 52, imageUrl: "Creamy_Onion_FOP_New_Image-500x500.webp" },
      { id: 28, tabId: "5", name: "Salty Punch", gujarati: "સોલ્ટી પંચ", price: 52, imageUrl: "SaltyPunch_FOP-500x500.webp" },
      { id: 29, tabId: "5", name: "Tomato Wafer", gujarati: "ટમેટા વેફર", price: 52, imageUrl: "Tomato_FOP-500x500.webp" },
      { id: 30, tabId: "5", name: "Farali chevdo tikho", gujarati: "ફરાળી ચેવડો તીખો", price: 51, imageUrl: "Farali-Chevdo_FOP-500x500.png" },
      { id: 31, tabId: "5", name: "Farali chevdo mitho", gujarati: "ફરાળી ચેવડો મીઠો", price: 51, imageUrl: "Farali-Mitha-Chevda-FOP-500x500-1-500x500.webp" },
      { id: 32, tabId: "5", name: "Vanela gathiya", gujarati: "વણેલા ગાંઠિયા", price: 51, imageUrl: "Vanela-Gathiya-1-500x500.png" },
      { id: 33, tabId: "5", name: "Bhakharwadi", gujarati: "ભાખરવડી", price: 51, imageUrl: "Bhakharvadi_FOP-500x500.png" },
      { id: 34, tabId: "5", name: "Tikha gathiya", gujarati: "તીખા ગાંઠિયા", price: 51, imageUrl: "TikhaGathiya_FOP-500x500.webp" },
      { id: 35, tabId: "5", name: "Ratlami sev", gujarati: "રતલામી સેવ", price: 51, imageUrl: "Gokul-Ratlami-Sev-400g-FOP-500x500.webp" },
      { id: 36, tabId: "5", name: "Sing bhujia", gujarati: "સીંગ ભુજીયા", price: 51, imageUrl: "SingBhujiya_FOP-500x500.webp" },
      { id: 37, tabId: "5", name: "Nylon chivda", gujarati: "નાયલોન ચેવડો", price: 51, imageUrl: "NylonSev-500x500.webp" },
      { id: 38, tabId: "5", name: "Masala Peanuts", gujarati: "મસાલા સીંગ", price: 51, imageUrl: "MasalaPeanuts_FOP-500x500.webp" },
      { id: 39, tabId: "5", name: "Crunchy bites (Kaju)", gujarati: "ક્રન્ચી બાઇટ્સ (કાજુ)", price: 51, imageUrl: "Crunchy-Bites-FOP-500x500.webp" },
      { id: 40, tabId: "5", name: "Lila toast", gujarati: "ઈલાયચી ટોસ્ટ", price: 102, imageUrl: "Elaichi-Toast-500x500.webp" },

      // ── Other ──
      { id: 41, tabId: "other", name: "Adad papad (₹10)", gujarati: "અડદ પાપડ (₹10)", price: 8, imageUrl: "Papad_FOP-500x500.png" },

      // ── 500g ──
      { id: 42, tabId: "500g", name: "Chanadal (500g)", gujarati: "ચણાદાળ (500g)", price: 60, imageUrl: "Chana-Dal_FOP-500x500.png" },
      { id: 43, tabId: "500g", name: "Dabela chana (500g)", gujarati: "દાબેલા ચણા (500g)", price: 60, imageUrl: "Dabela-Chana_FOP-500x500.png" },
      { id: 44, tabId: "500g", name: "Bhavnagari gathiya (500g)", gujarati: "ભાવનગરી ગાંઠિયા (500g)", price: 60, imageUrl: "Bhavnagri-Gathiya-FOP-500x500.webp" },
      { id: 45, tabId: "500g", name: "Nylon gathiya (500g)", gujarati: "નાયલોન ગાંઠિયા (500g)", price: 60, imageUrl: "NylonGathiya_FOP-500x500.webp" },
      { id: 46, tabId: "500g", name: "Vanela gathiya (500g)", gujarati: "વણેલા ગાંઠિયા (500g)", price: 60, imageUrl: "Vanela-Gathiya-1-500x500.png" },
      { id: 47, tabId: "500g", name: "Ratlami sev (500g)", gujarati: "રતલામી સેવ (500g)", price: 60, imageUrl: "Gokul-Ratlami-Sev-400g-FOP-500x500.webp" },
      { id: 48, tabId: "500g", name: "Sing bhujiya (500g)", gujarati: "સીંગ ભુજીયા (500g)", price: 75, imageUrl: "SingBhujiya_FOP-500x500.webp" },
      { id: 49, tabId: "500g", name: "Sakkarpara (500g)", gujarati: "સક્કરપારા (500g)", price: 60, imageUrl: "Sakkarpara_FOP-500x500.webp" },
      { id: 50, tabId: "500g", name: "Tikha mitha mix (500g)", gujarati: "તીખા મીઠા મિક્સ (500g)", price: 65, imageUrl: "Tikha-Mitha-Mix-FOP-500x500.webp" },
    ],
  },

  // ─────────────────────────── REAL ───────────────────────────
  {
    id: "real",
    name: "Real",
    logoUrl: "assets/images/real.png",
    cardVariant: "variant-2",
    defaultLanguage: "gujarati",
    imageFolder: "assets/images/realItems/",

    tabs: [
      { id: "real", label: "Real" },
      // { id: "5", label: "₹5 Items" },
      // { id: "10", label: "₹10 Items" },
      // { id: "20", label: "₹20 Items" },
      // { id: "30", label: "₹30 Items" },
      // { id: "40", label: "₹40 Items" },
      // { id: "200g", label: "200g" },
      // { id: "250g", label: "250g" },
      // { id: "350g", label: "350g" },
      // { id: "400g", label: "400g" },
      { id: "500g", label: "500g" }
    ],

    items: [

      // ───────────────────── EXISTING REAL LIST ─────────────────────

      { id: 1, tabId: "real", name: "Ratlami sev", gujarati: "રતલામી સેવ", price: 51, imageUrl: "Ratlami_Sev.png" },
      { id: 2, tabId: "real", name: "Aaloo sev", gujarati: "આલૂ સેવ", price: 51, imageUrl: "Aaloo_Sev.webp" },
      { id: 3, tabId: "real", name: "Sing bhujiya", gujarati: "સીંગ ભુજીયા", price: 51, imageUrl: "Sing_Bhujia_Bikaneri.png" },
      { id: 4, tabId: "real", name: "Moong dal", gujarati: "મૂંગ દાળ", price: 54, imageUrl: "Moong_Mogar.png" },
      { id: 5, tabId: "real", name: "Soya stick", gujarati: "સોયા સ્ટિક", price: 51, imageUrl: "Soya_Stick.png" },
      { id: 6, tabId: "real", name: "Soya chips", gujarati: "સોયા ચિપ્સ", price: 51, imageUrl: "Soya_Chips.png" },
      { id: 7, tabId: "real", name: "Tomato kurkure", gujarati: "ટોમેટો કુરકુરે", price: 51, imageUrl: "Tomato_Twist.png" },
      { id: 8, tabId: "real", name: "Masala kurkure", gujarati: "મસાલા કુરકુરે", price: 51, imageUrl: "Masala_Hit.png" },
      { id: 9, tabId: "real", name: "Mora sevmamra", gujarati: "મોરા સેવમમરા", price: 51, imageUrl: "Sev_Mamra.png" },
      { id: 10, tabId: "real", name: "Tikha sevmamra", gujarati: "તીખા સેવમમરા", price: 51, imageUrl: "Masala_Sev_Mamra.png" },
      { id: 11, tabId: "real", name: "Bhel mamra", gujarati: "ભેળ મમરા", price: 51, imageUrl: "Bhel_Mix.png" },
      { id: 12, tabId: "real", name: "Farali tikho", gujarati: "ફરાળી તીખો", price: 51, imageUrl: "Farali_Chiwda_Tikha.png" },
      { id: 13, tabId: "real", name: "Farali mitho", gujarati: "ફરાળી મીઠો", price: 54, imageUrl: "Farali_Chiwda_Mitha.png" },
      { id: 14, tabId: "real", name: "Tikhi papdi", gujarati: "તીખી પાપડી", price: 51, imageUrl: "Masala_Papdi.png" },
      { id: 15, tabId: "real", name: "Mori papdi", gujarati: "મોરી પાપડી", price: 51, imageUrl: "Papdi_Ganthiya.png" },
      { id: 16, tabId: "real", name: "Pasta", gujarati: "પાસ્તા", price: 51, imageUrl: "Penne_Masala.png" },
      { id: 17, tabId: "real", name: "Farali wafers", gujarati: "ફરાળી વેફર્સ", price: 54, imageUrl: "Farali_Wafers.png" },
      { id: 18, tabId: "real", name: "Mori wafers", gujarati: "મોરી વેફર્સ", price: 54, imageUrl: "Tasty_Salty.png" },
      { id: 19, tabId: "real", name: "Noodles", gujarati: "નૂડલ્સ", price: 50, imageUrl: "" },
      { id: 20, tabId: "real", name: "Polo ring", gujarati: "પોલો રીંગ", price: 50, imageUrl: "Masala_Ring.png" },
      { id: 21, tabId: "real", name: "Jeera papad", gujarati: "જીરા પાપડ", price: 50, imageUrl: "" },
      { id: 22, tabId: "real", name: "Tikha papad", gujarati: "તીખા પાપડ", price: 50, imageUrl: "" },
      { id: 23, tabId: "real", name: "Tarzan", gujarati: "ટાર્ઝન", price: 50, imageUrl: "" },
      { id: 24, tabId: "real", name: "Mora bhoongala", gujarati: "મોરા ભૂંગળા", price: 50, imageUrl: "Ponga.png" },
      { id: 25, tabId: "real", name: "Pani puri cup", gujarati: "પાણી પુરી કુરકુરે", price: 50, imageUrl: "Pani_Puri_Cup.png" },

      // // ───────────────────── ₹5 ITEMS ─────────────────────
      // { id: 26, tabId: "5", name: "Aaloo Sev (₹5)", gujarati: "આલૂ સેવ", price: 45, imageUrl: "Aaloo_Sev.webp" },
      // { id: 27, tabId: "5", name: "Bhavnagri Ganthiya (₹5)", gujarati: "ભાવનગરી ગાંઠિયા", price: 45, imageUrl: "Bhavnagri_Ganthiya.png" },
      // { id: 28, tabId: "5", name: "Bhel Mix (₹5)", gujarati: "ભેળ મિક્સ", price: 45, imageUrl: "Bhel_Mix.png" },
      // { id: 29, tabId: "5", name: "Bikaneri Sev (₹5)", gujarati: "બીકાનેરી સેવ", price: 45, imageUrl: "Bikaneri_Sev.png" },
      // { id: 30, tabId: "5", name: "Champakali Ganthiya (₹5)", gujarati: "ચંપાકલી ગાંઠિયા", price: 45, imageUrl: "Champakali_Ganthiya.png" },
      // { id: 31, tabId: "5", name: "Chana Dal (₹5)", gujarati: "ચણા દાળ", price: 45, imageUrl: "Chana_Dal.png" },
      // { id: 32, tabId: "5", name: "Chana Jor Garam (₹5)", gujarati: "ચણા જોર ગરમ", price: 45, imageUrl: "Chana_Jor_Garam.png" },
      // { id: 33, tabId: "5", name: "Cheesy Curl (₹5)", gujarati: "ચીઝી કર્લ", price: 45, imageUrl: "Cheesy_Curl.png" },
      // { id: 34, tabId: "5", name: "Cheesy Ring (₹5)", gujarati: "ચીઝી રીંગ", price: 45, imageUrl: "Cheesy_Ring.png" },
      // { id: 35, tabId: "5", name: "Chilli Chatka (₹5)", gujarati: "ચિલી ચટકા", price: 45, imageUrl: "Chilli_Chatka.png" },
      // { id: 36, tabId: "5", name: "Classic Sev (₹5)", gujarati: "ક્લાસિક સેવ", price: 45, imageUrl: "Classic_Sev.png" },
      // { id: 37, tabId: "5", name: "Cream & Onion (₹5)", gujarati: "ક્રીમ એન્ડ ઓનિયન", price: 45, imageUrl: "Cream_&_Onion.png" },
      // { id: 38, tabId: "5", name: "Farali Chiwda Mitha (₹5)", gujarati: "ફરાળી ચેવડો મીઠો", price: 45, imageUrl: "Farali_Chiwda_Mitha.png" },
      // { id: 39, tabId: "5", name: "Farali Chiwda Tikha (₹5)", gujarati: "ફરાળી ચેવડો તીખો", price: 45, imageUrl: "Farali_Chiwda_Tikha.png" },
      // { id: 40, tabId: "5", name: "Farali Wafers (₹5)", gujarati: "ફરાળી વેફર્સ", price: 45, imageUrl: "Farali_Wafers.png" },
      // { id: 41, tabId: "5", name: "Indori Mix (₹5)", gujarati: "ઇન્દોરી મિક્સ", price: 45, imageUrl: "Indori_Mix.png" },
      // { id: 42, tabId: "5", name: "Khat Mith (₹5)", gujarati: "ખાટમીઠ", price: 45, imageUrl: "Khat_Mith.png" },
      // { id: 43, tabId: "5", name: "Makai Chiwda (₹5)", gujarati: "મકાઈ ચેવડો", price: 45, imageUrl: "Makai_Chiwda.png" },
      // { id: 44, tabId: "5", name: "Masala Chana (₹5)", gujarati: "મસાલા ચણા", price: 45, imageUrl: "Masala_Chana.png" },
      // { id: 45, tabId: "5", name: "Masala Cup (₹5)", gujarati: "મસાલા કપ", price: 45, imageUrl: "Masala_Cup.png" },
      // { id: 46, tabId: "5", name: "Masala Hit (₹5)", gujarati: "મસાલા હિટ", price: 45, imageUrl: "Masala_Hit.png" },
      // { id: 47, tabId: "5", name: "Masala Papdi (₹5)", gujarati: "મસાલા પાપડી", price: 45, imageUrl: "Masala_Papdi.png" },
      // { id: 48, tabId: "5", name: "Masala Peanut (₹5)", gujarati: "મસાલા સીંગ", price: 45, imageUrl: "Masala_Peanut.png" },
      // { id: 49, tabId: "5", name: "Masala Punch (₹5)", gujarati: "મસાલા પંચ", price: 45, imageUrl: "Masala_Punch.png" },
      // { id: 50, tabId: "5", name: "Masala Ring (₹5)", gujarati: "મસાલા રીંગ", price: 45, imageUrl: "Masala_Ring.png" },
      // { id: 51, tabId: "5", name: "Masala Sev Mamra (₹5)", gujarati: "મસાલા સેવમમરા", price: 45, imageUrl: "Masala_Sev_Mamra.png" },
      // { id: 52, tabId: "5", name: "Moong Mogar (₹5)", gujarati: "મૂંગ મોગર", price: 45, imageUrl: "Moong_Mogar.png" },
      // { id: 53, tabId: "5", name: "Nadiadi Mix (₹5)", gujarati: "નડિયાદી મિક્સ", price: 45, imageUrl: "Nadiadi_Mix.png" },
      // { id: 54, tabId: "5", name: "Nimboo Pudina Peanuts (₹5)", gujarati: "લીંબુ ફુદીના સીંગ", price: 45, imageUrl: "Nimboo_Pudina_Peanuts.png" },
      // { id: 55, tabId: "5", name: "Pani Puri Cup (₹5)", gujarati: "પાણી પુરી કપ", price: 45, imageUrl: "Pani_Puri_Cup.png" },
      // { id: 56, tabId: "5", name: "Pani Puri Masala (₹5)", gujarati: "પાણી પુરી મસાલો", price: 45, imageUrl: "Pani_Puri_Masala.png" },
      // { id: 57, tabId: "5", name: "Papad Chawana (₹5)", gujarati: "પાપડ ચવાણા", price: 45, imageUrl: "Papad_Chawana.png" },
      // { id: 58, tabId: "5", name: "Papdi Ganthiya (₹5)", gujarati: "પાપડી ગાંઠિયા", price: 45, imageUrl: "Papdi_Ganthiya.png" },
      // { id: 59, tabId: "5", name: "Pauva Chiwda (₹5)", gujarati: "પૌવા ચેવડો", price: 45, imageUrl: "Pauva_Chiwda.png" },
      // { id: 60, tabId: "5", name: "Peanut Butter Chikki (₹5)", gujarati: "પીનટ બટર ચીક્કી", price: 45, imageUrl: "Peanut_Butter_Chikki.png" },
      // { id: 61, tabId: "5", name: "Peanut Chikki (₹5)", gujarati: "સીંગ ચીક્કી", price: 45, imageUrl: "Peanut_Chikki.png" },
      // { id: 62, tabId: "5", name: "Penne Masala (₹5)", gujarati: "પેને મસાલા", price: 45, imageUrl: "Penne_Masala.png" },
      // { id: 63, tabId: "5", name: "Peri Peri Masala (₹5)", gujarati: "પેરી પેરી મસાલો", price: 45, imageUrl: "Peri_Peri_Masala.png" },
      // { id: 64, tabId: "5", name: "Ponga (₹5)", gujarati: "પોંગા", price: 45, imageUrl: "Ponga.png" },
      // { id: 65, tabId: "5", name: "Premium Rusk (₹5)", gujarati: "પ્રીમિયમ રસ્ક", price: 45, imageUrl: "Premium_Rusk.png" },
      // { id: 66, tabId: "5", name: "Ratlami Sev (₹5)", gujarati: "રતલામી સેવ", price: 45, imageUrl: "Ratlami_Sev.png" },
      // { id: 67, tabId: "5", name: "Salt & Pepper (₹5)", gujarati: "સોલ્ટ એન્ડ પેપર", price: 45, imageUrl: "Salt_&_Pepper.png" },
      // { id: 68, tabId: "5", name: "Salted Peanuts (₹5)", gujarati: "મીઠી સીંગ", price: 45, imageUrl: "Salted_Peanuts.png" },
      // { id: 69, tabId: "5", name: "Sev Mamra (₹5)", gujarati: "સેવમમરા", price: 45, imageUrl: "Sev_Mamra.png" },
      // { id: 70, tabId: "5", name: "Sing Bhujia Bikaneri (₹5)", gujarati: "સીંગ ભુજીયા બીકાનેરી", price: 45, imageUrl: "Sing_Bhujia_Bikaneri.png" },
      // { id: 71, tabId: "5", name: "Soya Chips (₹5)", gujarati: "સોયા ચિપ્સ", price: 45, imageUrl: "Soya_Chips.png" },
      // { id: 72, tabId: "5", name: "Soya Stick (₹5)", gujarati: "સોયા સ્ટિક", price: 45, imageUrl: "Soya_Stick.png" },
      // { id: 73, tabId: "5", name: "Surti Mix (₹5)", gujarati: "સુરતી મિક્સ", price: 45, imageUrl: "Surti_Mix.jpg" },
      // { id: 74, tabId: "5", name: "Tasty Salty (₹5)", gujarati: "ટેસ્ટી સોલ્ટી", price: 45, imageUrl: "Tasty_Salty.png" },
      // { id: 75, tabId: "5", name: "Tikha Mitha Mix (₹5)", gujarati: "તીખા મીઠા મિક્સ", price: 45, imageUrl: "Tikha_Mitha_Mix.png" },
      // { id: 76, tabId: "5", name: "Tomato Cup (₹5)", gujarati: "ટોમેટો કપ", price: 45, imageUrl: "Tomato_Cup.png" },
      // { id: 77, tabId: "5", name: "Tomato Rings (₹5)", gujarati: "ટોમેટો રીંગ્સ", price: 45, imageUrl: "Tomato_Rings.png" },
      // { id: 78, tabId: "5", name: "Tomato Treat (₹5)", gujarati: "ટોમેટો ટ્રીટ", price: 45, imageUrl: "Tomato_Treat.png" },
      // { id: 79, tabId: "5", name: "Tomato Twist (₹5)", gujarati: "ટોમેટો ટ્વિસ્ટ", price: 45, imageUrl: "Tomato_Twist.png" },
      // { id: 80, tabId: "5", name: "Tutti Frutti Rusk (₹5)", gujarati: "ટુટી ફ્રૂટી રસ્ક", price: 45, imageUrl: "Tutti_Frutti_Rusk.png" },
      // { id: 81, tabId: "5", name: "Usal Ganthiya (₹5)", gujarati: "ઉસળ ગાંઠિયા", price: 45, imageUrl: "Usal_Ganthiya.png" },
      // { id: 82, tabId: "5", name: "Wheelers Masala (₹5)", gujarati: "વ્હીલર્સ મસાલા", price: 45, imageUrl: "Wheelers_Masala.png" },
      // { id: 83, tabId: "5", name: "Yum Noodles (₹5)", gujarati: "યમ નૂડલ્સ", price: 45, imageUrl: "Yum_Noodles.png" },

      // // ───────────────────── ₹10 ITEMS ─────────────────────

      // { id: 84, tabId: "10", name: "Aaloo Sev (₹10)", gujarati: "આલૂ સેવ", price: 90, imageUrl: "Aaloo_Sev.webp" },
      // { id: 85, tabId: "10", name: "Banana Wafers (₹10)", gujarati: "બનાના વેફર્સ", price: 90, imageUrl: "Banana_Wafers.png" },
      // { id: 86, tabId: "10", name: "Bhavnagri Ganthiya (₹10)", gujarati: "ભાવનગરી ગાંઠિયા", price: 90, imageUrl: "Bhavnagri_Ganthiya.png" },
      // { id: 87, tabId: "10", name: "Bhel Mix (₹10)", gujarati: "ભેળ મિક્સ", price: 90, imageUrl: "Bhel_Mix.png" },
      // { id: 88, tabId: "10", name: "Bikaneri Sev (₹10)", gujarati: "બીકાનેરી સેવ", price: 90, imageUrl: "Bikaneri_Sev.png" },
      // { id: 89, tabId: "10", name: "Chana Dal (₹10)", gujarati: "ચણા દાળ", price: 90, imageUrl: "Chana_Dal.png" },
      // { id: 90, tabId: "10", name: "Chana Jor Garam (₹10)", gujarati: "ચણા જોર ગરમ", price: 90, imageUrl: "Chana_Jor_Garam.png" },
      // { id: 91, tabId: "10", name: "Chilli Chatka (₹10)", gujarati: "ચિલી ચટકા", price: 90, imageUrl: "Chilli_Chatka.png" },
      // { id: 92, tabId: "10", name: "Chocolate (₹10)", gujarati: "ચોકલેટ", price: 90, imageUrl: "Chocolate.png" },
      // { id: 93, tabId: "10", name: "Classic Sev (₹10)", gujarati: "ક્લાસિક સેવ", price: 90, imageUrl: "Classic_Sev.png" },
      // { id: 94, tabId: "10", name: "Cream & Onion (₹10)", gujarati: "ક્રીમ એન્ડ ઓનિયન", price: 90, imageUrl: "Cream_&_Onion.png" },
      // { id: 95, tabId: "10", name: "Farali Chiwda Mitha (₹10)", gujarati: "ફરાળી ચેવડો મીઠો", price: 90, imageUrl: "Farali_Chiwda_Mitha.png" },
      // { id: 96, tabId: "10", name: "Farali Chiwda Tikha (₹10)", gujarati: "ફરાળી ચેવડો તીખો", price: 90, imageUrl: "Farali_Chiwda_Tikha.png" },
      // { id: 97, tabId: "10", name: "Farali Wafers (₹10)", gujarati: "ફરાળી વેફર્સ", price: 90, imageUrl: "Farali_Wafers.png" },
      // { id: 98, tabId: "10", name: "Indori Mix (₹10)", gujarati: "ઇન્દોરી મિક્સ", price: 90, imageUrl: "Indori_Mix.png" },
      // { id: 99, tabId: "10", name: "Jeera Salty Rusk (₹10)", gujarati: "જીરા સોલ્ટી રસ્ક", price: 90, imageUrl: "Jeera_Salty_Rusk.png" },
      // { id: 100, tabId: "10", name: "Khat Mith (₹10)", gujarati: "ખાટમીઠ", price: 90, imageUrl: "Khat_Mith.png" },
      // { id: 101, tabId: "10", name: "Masala Hit (₹10)", gujarati: "મસાલા હિટ", price: 90, imageUrl: "Masala_Hit.png" },
      // { id: 102, tabId: "10", name: "Masala Punch (₹10)", gujarati: "મસાલા પંચ", price: 90, imageUrl: "Masala_Punch.png" },
      // { id: 103, tabId: "10", name: "Milk Rusk (₹10)", gujarati: "મિલ્ક રસ્ક", price: 90, imageUrl: "Milk_Rusk.png" },
      // { id: 104, tabId: "10", name: "Moong Mogar (₹10)", gujarati: "મૂંગ મોગર", price: 90, imageUrl: "Moong_Mogar.png" },
      // { id: 105, tabId: "10", name: "Nadiadi Mix (₹10)", gujarati: "નડિયાદી મિક્સ", price: 90, imageUrl: "Nadiadi_Mix.png" },
      // { id: 106, tabId: "10", name: "Pani Puri Masala (₹10)", gujarati: "પાણી પુરી મસાલો", price: 90, imageUrl: "Pani_Puri_Masala.png" },
      // { id: 107, tabId: "10", name: "Papad Chawana (₹10)", gujarati: "પાપડ ચવાણા", price: 90, imageUrl: "Papad_Chawana.png" },
      // { id: 108, tabId: "10", name: "Papdi Ganthiya (₹10)", gujarati: "પાપડી ગાંઠિયા", price: 90, imageUrl: "Papdi_Ganthiya.png" },
      // { id: 109, tabId: "10", name: "Peri Peri Masala (₹10)", gujarati: "પેરી પેરી મસાલો", price: 90, imageUrl: "Peri_Peri_Masala.png" },
      // { id: 110, tabId: "10", name: "Premium Rusk (₹10)", gujarati: "પ્રીમિયમ રસ્ક", price: 90, imageUrl: "Premium_Rusk.png" },
      // { id: 111, tabId: "10", name: "Ratlami Sev (₹10)", gujarati: "રતલામી સેવ", price: 90, imageUrl: "Ratlami_Sev.png" },
      // { id: 112, tabId: "10", name: "Salt & Pepper (₹10)", gujarati: "સોલ્ટ એન્ડ પેપર", price: 90, imageUrl: "Salt_&_Pepper.png" },
      // { id: 113, tabId: "10", name: "Sev Mamra (₹10)", gujarati: "સેવમમરા", price: 90, imageUrl: "Sev_Mamra.png" },
      // { id: 114, tabId: "10", name: "Sing Bhujia Bikaneri (₹10)", gujarati: "સીંગ ભુજીયા બીકાનેરી", price: 90, imageUrl: "Sing_Bhujia_Bikaneri.png" },
      // { id: 115, tabId: "10", name: "Soya Chips (₹10)", gujarati: "સોયા ચિપ્સ", price: 90, imageUrl: "Soya_Chips.png" },
      // { id: 116, tabId: "10", name: "Soya Stick (₹10)", gujarati: "સોયા સ્ટિક", price: 90, imageUrl: "Soya_Stick.png" },
      // { id: 117, tabId: "10", name: "Strawberry (₹10)", gujarati: "સ્ટ્રોબેરી", price: 90, imageUrl: "Strawberry.png" },
      // { id: 118, tabId: "10", name: "Tasty Salty (₹10)", gujarati: "ટેસ્ટી સોલ્ટી", price: 90, imageUrl: "Tasty_Salty.png" },
      // { id: 119, tabId: "10", name: "Tea Time Rusk (₹10)", gujarati: "ટી ટાઈમ રસ્ક", price: 90, imageUrl: "Tea_Time_Rusk.png" },
      // { id: 120, tabId: "10", name: "Tikha Mitha Mix (₹10)", gujarati: "તીખા મીઠા મિક્સ", price: 90, imageUrl: "Tikha_Mitha_Mix.png" },
      // { id: 121, tabId: "10", name: "Tomato Treat (₹10)", gujarati: "ટોમેટો ટ્રીટ", price: 90, imageUrl: "Tomato_Treat.png" },
      // { id: 122, tabId: "10", name: "Tomato Twist (₹10)", gujarati: "ટોમેટો ટ્વિસ્ટ", price: 90, imageUrl: "Tomato_Twist.png" },
      // { id: 123, tabId: "10", name: "Vanilla (₹10)", gujarati: "વેનિલા", price: 90, imageUrl: "Vanilla.png" },

      // // ───────────────────── ₹20 ITEMS ─────────────────────

      // { id: 184, tabId: "20", name: "Khari (₹20)", gujarati: "ખારી", price: 180, imageUrl: "Khari.png" },

      // // ───────────────────── ₹30 ITEMS ─────────────────────

      // { id: 124, tabId: "30", name: "Farali Cookies (₹30)", gujarati: "ફરાળી કૂકીઝ", price: 270, imageUrl: "Farali_Cookies.png" },

      // // ───────────────────── ₹40 ITEMS ─────────────────────

      // { id: 125, tabId: "40", name: "Farali Wafers (₹40)", gujarati: "ફરાળી વેફર્સ", price: 360, imageUrl: "Farali_Wafers.png" },
      // { id: 126, tabId: "40", name: "Masala Punch (₹40)", gujarati: "મસાલા પંચ", price: 360, imageUrl: "Masala_Punch.png" },
      // { id: 127, tabId: "40", name: "Tasty Salty (₹40)", gujarati: "ટેસ્ટી સોલ્ટી", price: 360, imageUrl: "Tasty_Salty.png" },

      // // ───────────────────── 200g ─────────────────────

      // { id: 128, tabId: "200g", name: "Aaloo Sev (200g)", gujarati: "આલૂ સેવ", price: 70, imageUrl: "Aaloo_Sev.webp" },
      // { id: 129, tabId: "200g", name: "Bhavnagri Ganthiya (200g)", gujarati: "ભાવનગરી ગાંઠિયા", price: 70, imageUrl: "Bhavnagri_Ganthiya.png" },
      // { id: 130, tabId: "200g", name: "Bhel Mix (200g)", gujarati: "ભેળ મિક્સ", price: 70, imageUrl: "Bhel_Mix.png" },
      // { id: 131, tabId: "200g", name: "Bikaneri Sev (200g)", gujarati: "બીકાનેરી સેવ", price: 70, imageUrl: "Bikaneri_Sev.png" },
      // { id: 132, tabId: "200g", name: "Chana Dal (200g)", gujarati: "ચણા દાળ", price: 70, imageUrl: "Chana_Dal.png" },
      // { id: 133, tabId: "200g", name: "Chana Jor Garam (200g)", gujarati: "ચણા જોર ગરમ", price: 70, imageUrl: "Chana_Jor_Garam.png" },
      // { id: 134, tabId: "200g", name: "Classic Sev (200g)", gujarati: "ક્લાસિક સેવ", price: 70, imageUrl: "Classic_Sev.png" },
      // { id: 135, tabId: "200g", name: "Farali Chiwda Mitha (200g)", gujarati: "ફરાળી ચેવડો મીઠો", price: 70, imageUrl: "Farali_Chiwda_Mitha.png" },
      // { id: 136, tabId: "200g", name: "Farali Chiwda Tikha (200g)", gujarati: "ફરાળી ચેવડો તીખો", price: 70, imageUrl: "Farali_Chiwda_Tikha.png" },
      // { id: 137, tabId: "200g", name: "Indori Mix (200g)", gujarati: "ઇન્દોરી મિક્સ", price: 70, imageUrl: "Indori_Mix.png" },
      // { id: 138, tabId: "200g", name: "Jeera Butter Khari (200g)", gujarati: "જીરા બટર ખારી", price: 70, imageUrl: "Jeera_Butter_Khari.png" },
      // { id: 139, tabId: "200g", name: "Jeera Salty Rusk (200g)", gujarati: "જીરા સોલ્ટી રસ્ક", price: 70, imageUrl: "Jeera_Salty_Rusk.png" },
      // { id: 140, tabId: "200g", name: "Khat Mith (200g)", gujarati: "ખાટમીઠ", price: 70, imageUrl: "Khat_Mith.png" },
      // { id: 141, tabId: "200g", name: "Khari (200g)", gujarati: "ખારી", price: 70, imageUrl: "Khari.png" },
      // { id: 142, tabId: "200g", name: "Masala Khari (200g)", gujarati: "મસાલા ખારી", price: 70, imageUrl: "Masala_Khari.png" },
      // { id: 143, tabId: "200g", name: "Methi Khari (200g)", gujarati: "મેથી ખારી", price: 70, imageUrl: "Methi_Khari.png" },
      // { id: 144, tabId: "200g", name: "Milk Rusk (200g)", gujarati: "મિલ્ક રસ્ક", price: 70, imageUrl: "Milk_Rusk.png" },
      // { id: 145, tabId: "200g", name: "Moong Mogar (200g)", gujarati: "મૂંગ મોગર", price: 70, imageUrl: "Moong_Mogar.png" },
      // { id: 146, tabId: "200g", name: "Nadiadi Mix (200g)", gujarati: "નડિયાદી મિક્સ", price: 70, imageUrl: "Nadiadi_Mix.png" },
      // { id: 147, tabId: "200g", name: "Papad Chawana (200g)", gujarati: "પાપડ ચવાણા", price: 70, imageUrl: "Papad_Chawana.png" },
      // { id: 148, tabId: "200g", name: "Premium Rusk (200g)", gujarati: "પ્રીમિયમ રસ્ક", price: 70, imageUrl: "Premium_Rusk.png" },
      // { id: 149, tabId: "200g", name: "Ratlami Sev (200g)", gujarati: "રતલામી સેવ", price: 70, imageUrl: "Ratlami_Sev.png" },
      // { id: 150, tabId: "200g", name: "Sev Mamra (200g)", gujarati: "સેવમમરા", price: 70, imageUrl: "Sev_Mamra.png" },
      // { id: 151, tabId: "200g", name: "Sing Bhujia Bikaneri (200g)", gujarati: "સીંગ ભુજીયા બીકાનેરી", price: 70, imageUrl: "Sing_Bhujia_Bikaneri.png" },
      // { id: 152, tabId: "200g", name: "Soya Chips (200g)", gujarati: "સોયા ચિપ્સ", price: 70, imageUrl: "Soya_Chips.png" },
      // { id: 153, tabId: "200g", name: "Soya Stick (200g)", gujarati: "સોયા સ્ટિક", price: 70, imageUrl: "Soya_Stick.png" },
      // { id: 154, tabId: "200g", name: "Tikha Mitha Mix (200g)", gujarati: "તીખા મીઠા મિક્સ", price: 70, imageUrl: "Tikha_Mitha_Mix.png" },

      // // ───────────────────── 250g ─────────────────────

      // { id: 155, tabId: "250g", name: "Chocolate Chips (250g)", gujarati: "ચોકલેટ ચિપ્સ", price: 85, imageUrl: "Chocolate_Chips.png" },
      // { id: 156, tabId: "250g", name: "Farali Cookies (250g)", gujarati: "ફરાળી કૂકીઝ", price: 85, imageUrl: "Farali_Cookies.png" },
      // { id: 157, tabId: "250g", name: "Pista Badam (250g)", gujarati: "પિસ્તા બદામ", price: 85, imageUrl: "Pista_Badam.png" },
      // { id: 158, tabId: "250g", name: "Pure Ghee Nankhatai (250g)", gujarati: "શુદ્ધ ઘી નાનખટાઈ", price: 85, imageUrl: "Pure_Ghee_Nankhatai.png" },
      // { id: 159, tabId: "250g", name: "Whole Wheat Cookies (250g)", gujarati: "હોલ વ્હીટ કૂકીઝ", price: 85, imageUrl: "Whole_Wheat_Cookies.png" },
      // { id: 160, tabId: "250g", name: "Whole Wheat Nankhatai (250g)", gujarati: "હોલ વ્હીટ નાનખટાઈ", price: 85, imageUrl: "Whole_Wheat_Nankhatai.png" },

      // // ───────────────────── 350g ─────────────────────

      // { id: 161, tabId: "350g", name: "Bhavnagri Ganthiya (350g)", gujarati: "ભાવનગરી ગાંઠિયા", price: 115, imageUrl: "Bhavnagri_Ganthiya.png" },
      // { id: 162, tabId: "350g", name: "Papdi Ganthiya (350g)", gujarati: "પાપડી ગાંઠિયા", price: 115, imageUrl: "Papdi_Ganthiya.png" },

      // // ───────────────────── 400g ─────────────────────

      // { id: 163, tabId: "400g", name: "Aaloo Sev (400g)", gujarati: "આલૂ સેવ", price: 135, imageUrl: "Aaloo_Sev.webp" },
      // { id: 164, tabId: "400g", name: "Bhavnagri Ganthiya (400g)", gujarati: "ભાવનગરી ગાંઠિયા", price: 135, imageUrl: "Bhavnagri_Ganthiya.png" },
      // { id: 165, tabId: "400g", name: "Bhel Mix (400g)", gujarati: "ભેળ મિક્સ", price: 135, imageUrl: "Bhel_Mix.png" },
      // { id: 166, tabId: "400g", name: "Bikaneri Sev (400g)", gujarati: "બીકાનેરી સેવ", price: 135, imageUrl: "Bikaneri_Sev.png" },
      // { id: 167, tabId: "400g", name: "Chana Dal (400g)", gujarati: "ચણા દાળ", price: 135, imageUrl: "Chana_Dal.png" },
      // { id: 168, tabId: "400g", name: "Chana Jor Garam (400g)", gujarati: "ચણા જોર ગરમ", price: 135, imageUrl: "Chana_Jor_Garam.png" },
      // { id: 169, tabId: "400g", name: "Classic Sev (400g)", gujarati: "ક્લાસિક સેવ", price: 135, imageUrl: "Classic_Sev.png" },
      // { id: 170, tabId: "400g", name: "Farali Chiwda Mitha (400g)", gujarati: "ફરાળી ચેવડો મીઠો", price: 135, imageUrl: "Farali_Chiwda_Mitha.png" },
      // { id: 171, tabId: "400g", name: "Farali Chiwda Tikha (400g)", gujarati: "ફરાળી ચેવડો તીખો", price: 135, imageUrl: "Farali_Chiwda_Tikha.png" },
      // { id: 172, tabId: "400g", name: "Indori Mix (400g)", gujarati: "ઇન્દોરી મિક્સ", price: 135, imageUrl: "Indori_Mix.png" },
      // { id: 173, tabId: "400g", name: "Masala Khari (400g)", gujarati: "મસાલા ખારી", price: 135, imageUrl: "Masala_Khari.png" },
      // { id: 174, tabId: "400g", name: "Methi Khari (400g)", gujarati: "મેથી ખારી", price: 135, imageUrl: "Methi_Khari.png" },
      // { id: 175, tabId: "400g", name: "Moong Mogar (400g)", gujarati: "મૂંગ મોગર", price: 135, imageUrl: "Moong_Mogar.png" },
      // { id: 176, tabId: "400g", name: "Nadiadi Mix (400g)", gujarati: "નડિયાદી મિક્સ", price: 135, imageUrl: "Nadiadi_Mix.png" },
      // { id: 177, tabId: "400g", name: "Ratlami Sev (400g)", gujarati: "રતલામી સેવ", price: 135, imageUrl: "Ratlami_Sev.png" },
      // { id: 178, tabId: "400g", name: "Sev Mamra (400g)", gujarati: "સેવમમરા", price: 135, imageUrl: "Sev_Mamra.png" },
      // { id: 179, tabId: "400g", name: "Sing Bhujia Bikaneri (400g)", gujarati: "સીંગ ભુજીયા બીકાનેરી", price: 135, imageUrl: "Sing_Bhujia_Bikaneri.png" },
      // { id: 180, tabId: "400g", name: "Soya Chips (400g)", gujarati: "સોયા ચિપ્સ", price: 135, imageUrl: "Soya_Chips.png" },
      // { id: 181, tabId: "400g", name: "Soya Stick (400g)", gujarati: "સોયા સ્ટિક", price: 135, imageUrl: "Soya_Stick.png" },
      // { id: 182, tabId: "400g", name: "Tikha Mitha Mix (400g)", gujarati: "તીખા મીઠા મિક્સ", price: 135, imageUrl: "Tikha_Mitha_Mix.png" },

      // // ───────────────────── 500g ─────────────────────

      { id: 183, tabId: "500g", name: "Carnival Cookies (500g)", gujarati: "કાર્નિવલ કૂકીઝ", price: 165, imageUrl: "Carnival_Cookies.png" }
    ]
  },

  // ─────────────────────────── BALAJI ─────────────────────────
  {
    id: "balaji",
    name: "Balaji",
    logoUrl: "assets/images/balaji.png",
    cardVariant: "variant-3",
    defaultLanguage: "english",
    imageFolder: "assets/images/balajiItems/",

    tabs: [],

    items: [
      { id: 1, tabId: null, name: "Wafers–simply salted", gujarati: null, price: 51 },
      { id: 2, tabId: null, name: "Wafers–masala masti", gujarati: null, price: 51 },
      { id: 3, tabId: null, name: "Wafers–tomato twist", gujarati: null, price: 51 },
      { id: 4, tabId: null, name: "Wafers–chaat chaska", gujarati: null, price: 51 },
      { id: 5, tabId: null, name: "Wafers–cream & onion", gujarati: null, price: 51 },
      { id: 6, tabId: null, name: "Peri peri wafers", gujarati: null, price: 51 },
      { id: 7, tabId: null, name: "Wafers–pizzy masala", gujarati: null, price: 51 },
      { id: 8, tabId: null, name: "Crunchex-simply salted", gujarati: null, price: 51 },
      { id: 9, tabId: null, name: "Crunchex-chilli tadka", gujarati: null, price: 51 },
      { id: 10, tabId: null, name: "Rumbles–pudina twist", gujarati: null, price: 51 },
      { id: 11, tabId: null, name: "Banana wafers–masala", gujarati: null, price: 51 },
      { id: 12, tabId: null, name: "Banana wafers–mari", gujarati: null, price: 51 },
      { id: 13, tabId: null, name: "Gippi noodles", gujarati: null, price: 51 },
      { id: 14, tabId: null, name: "Yumstix", gujarati: null, price: 51 },
      { id: 15, tabId: null, name: "Punjabi tadka", gujarati: null, price: 51 },
      { id: 16, tabId: null, name: "Flamin hot nachos", gujarati: null, price: 51 },
      { id: 17, tabId: null, name: "Cheese chilli nachos", gujarati: null, price: 51 },
      { id: 18, tabId: null, name: "Funne–spicy punch", gujarati: null, price: 51 },
      { id: 19, tabId: null, name: "Scoopitos", gujarati: null, price: 51 },
      { id: 20, tabId: null, name: "Poprings–yummy cheese", gujarati: null, price: 51 },
      { id: 21, tabId: null, name: "Poprings–masala", gujarati: null, price: 51 },
      { id: 22, tabId: null, name: "Wheelos–masala", gujarati: null, price: 51 },
      { id: 23, tabId: null, name: "Cp–flamin' hot", gujarati: null, price: 51 },
      { id: 24, tabId: null, name: "Cp–chinese chaska", gujarati: null, price: 51 },
      { id: 25, tabId: null, name: "Cp–tangy tomato", gujarati: null, price: 51 },
      { id: 26, tabId: null, name: "Cp–masala masti", gujarati: null, price: 51 },
      { id: 27, tabId: null, name: "Khata mitha mix", gujarati: null, price: 51 },
      { id: 28, tabId: null, name: "Tikha mitha mix", gujarati: null, price: 51 },
      { id: 29, tabId: null, name: "Mitha farali chiwda", gujarati: null, price: 51 },
      { id: 30, tabId: null, name: "Farali chevdo", gujarati: null, price: 51 },
      { id: 31, tabId: null, name: "Chana jor garam", gujarati: null, price: 51 },
      { id: 32, tabId: null, name: "Bhel mix", gujarati: null, price: 51 },
      { id: 33, tabId: null, name: "Mung dal", gujarati: null, price: 51 },
      { id: 34, tabId: null, name: "Chana dal", gujarati: null, price: 51 },
      { id: 35, tabId: null, name: "Masala peas", gujarati: null, price: 51 },
      { id: 36, tabId: null, name: "Shing bhujia", gujarati: null, price: 51 },
      { id: 37, tabId: null, name: "Nimbu s.B.", gujarati: null, price: 51 },
      { id: 38, tabId: null, name: "Salted peanuts", gujarati: null, price: 51 },
      { id: 39, tabId: null, name: "Masala shing", gujarati: null, price: 51 },
      { id: 40, tabId: null, name: "Aloo sev", gujarati: null, price: 51 },
      { id: 41, tabId: null, name: "Classic sev", gujarati: null, price: 51 },
      { id: 42, tabId: null, name: "Gathiya", gujarati: null, price: 51 },
      { id: 43, tabId: null, name: "Ratlami sev", gujarati: null, price: 51 },
      { id: 44, tabId: null, name: "Sev murmura", gujarati: null, price: 51 },
      { id: 45, tabId: null, name: "Masala sev murmura", gujarati: null, price: 51 },
    ],
  },
];
