export const realItemsList = [
  { name: "Ratlami sev", price: 51 },
  { name: "Aaloo sev", price: 51 },
  { name: "Sing bhujiya", price: 51 },
  { name: "Moong dal", price: 54 },
  { name: "Soya stick", price: 51 },
  { name: "Soya chips", price: 51 },
  { name: "Tomato kurkure", price: 51 },
  { name: "Masala kurkure", price: 51 },
  { name: "Mora sevmamra", price: 51 },
  { name: "Tikha sevmamra", price: 51 },
  { name: "Bhel mamra", price: 51 },
  { name: "Farali tikho", price: 51 },
  { name: "Farali mitho", price: 54 },
  { name: "Tikhi papdi", price: 51 },
  { name: "Mori papdi", price: 51 },
  { name: "Pasta", price: 51 },
  { name: "Farali wafers", price: 54 },
  { name: "Mori wafers", price: 54 },
  { name: "Noodles", price: 50 },
  { name: "Polo ring", price: 50 },
  { name: "Jeera papad", price: 50 },
  { name: "Tikha papad", price: 50 },
  { name: "Tarzan", price: 50 },
  { name: "Mora bhoongala", price: 50 },
  { name: "Pani puri cup", price: 50 },
];

export const realItemsListGujarati = [
  { name: "રતલામી સેવ", price: 51 },
  { name: "આલૂ સેવ", price: 51 },
  { name: "સીંગ ભુજીયા", price: 51 },
  { name: "મૂંગ દાળ", price: 54 },
  { name: "સોયા સ્ટિક", price: 51 },
  { name: "સોયા ચિપ્સ", price: 51 },
  { name: "ટોમેટો કુરકુરે", price: 51 },
  { name: "વાડકા", price: 52 },
  { name: "પાણીપુરી વાડકા", price: 52 },
  { name: "મસાલા કુરકુરે", price: 51 },
  { name: "મોરા  સેવમમરા", price: 51 },
  { name: "તીખા સેવમમરા", price: 51 },
  { name: "ભેળ મમરા", price: 51 },
  { name: "ફરાળી તીખો", price: 51 },
  { name: "ફરાળી મીઠો", price: 54 },
  { name: "તીખી પાપડી", price: 51 },
  { name: "મોરી પાપડી", price: 51 },
  { name: "પાસ્તા", price: 51 },
  { name: "ફરાળી વેફર્સ", price: 54 },
  { name: "મોરી વેફર્સ", price: 54 },
  { name: "તીખી વેફર્સ", price: 54 },
  { name: "નૂડલ્સ", price: 50 },
  { name: "પોલો રીંગ", price: 50 },
  { name: "જીરા પાપડ", price: 50 },
  { name: "તીખા પાપડ", price: 50 },
  { name: "ટાર્ઝન", price: 50 },
  { name: "મોરા ભૂંગળા", price: 52 },
  { name: "પાણી પુરી કુરકુરે", price: 51 },
  { name: "ચાના દાળ", price: 51 },
  { name: "ચાના ચોર ગરમ", price: 51 },
  { name: "ગાંઠિયા", price: 51 },
  { name: "બીકાનેરી સેવ", price: 51 },
  { name: "મસાલા સીંગ", price: 51 },
  { name: "પંજાબી તડકા", price: 51 },
  { name: "ખટ્ટ મીઠ ચવાણું", price: 51 },
  { name: "નડિયાદી મિક્સ", price: 51 },
  { name: "ઇન્દોરી મિક્સ", price: 51 },
  { name: "પાપડ ચવાણું", price: 51 },
  { name: "પૌવા ચેવડા", price: 51 },
  { name: "મકાઈ ચેવડા", price: 51 },
  { name: "તીખા મીઠા મિક્સ", price: 51 },
  { name: "ઇનામ", price: 50 },
];

export const gokulItemsList = [
  { id: 1, name: "Masala cup", originalName: "Masala Cup", price: 52, imageUrl: "Masala_Cup_Front-_image-500x500.png" },
  { id: 2, name: "Tomato cup", originalName: "Tomato Cup", price: 52, imageUrl: "Tomato_Cup_Front_image-500x500.png" },
  { id: 3, name: "Plane", originalName: "Aeroplane", price: 52, imageUrl: "Aeroplan_Front_image-500x500.png" },
  { id: 4, name: "ABCD", originalName: "Alphabet", price: 52, imageUrl: "Alphabet_Front_img-500x500.png" },
  { id: 5, name: "Chowkadi", originalName: "Chowkadi", price: 52, imageUrl: "Chowkadi_Front_image-500x500.png" },
  { id: 6, name: "Plain ponga", originalName: "Ponga", price: 52, imageUrl: "Gokul-Ponga-Front-lq-500x500.png" },
  { id: 7, name: "Wheels", originalName: "Wheels", price: 52, imageUrl: "Wheels-FOP-500x500.png" },
  { id: 8, name: "Pasta", originalName: "Pasta", price: 52, imageUrl: "Pasta-FOP-500x500.png" },
  { id: 9, name: "Trayo", originalName: "Trayo", price: 52, imageUrl: "Trayo-FOP-500x500.png" },
  { id: 10, name: "Raw Trayo", originalName: "Raw Trayo", price: 52, imageUrl: "Raw_Trayo_Image-500x500.webp" },
  { id: 11, name: "PopCorn", originalName: "Popcorn", price: 52, imageUrl: "Popcorn_Final_FOP-500x500.webp" },
  { id: 12, name: "Corn V Garlic Chilli", originalName: "Garlic Chilli Corn V", price: 52, imageUrl: "Gokul-Garlic-Chilli-Corn-V-Rs.5-Mockup-Pouch_Front-500x500.jpg" },
  { id: 13, name: "Masala Corn V", originalName: "Masala Corn V", price: 52, imageUrl: "Corn-Masala-FOP-500x500.webp" },
  { id: 14, name: "Tomato Corn V", originalName: "Tomato Corn V", price: 52, imageUrl: "Corn-Tomato-FOP-500x500.webp" },
  { id: 15, name: "Bhavnagri gathiya", originalName: "Bhavnagri Gathiya", price: 51, imageUrl: "Bhavnagri-Gathiya-FOP-500x500.webp" },
  { id: 16, name: "Nylon gathiya", originalName: "Nylon Gathiya", price: 51, imageUrl: "NylonGathiya_FOP-500x500.webp" },
  { id: 17, name: "Sev", originalName: "Sev", price: 51, imageUrl: "Sev_FOP-500x500.webp" },
  { id: 18, name: "Papdi", originalName: "Papdi Gathiya", price: 51, imageUrl: "PapdiGathiya_FOP-500x500.webp" },
  { id: 19, name: "Tikha mitha mix", originalName: "Tikha Mitha Mix", price: 51, imageUrl: "Tikha-Mitha-Mix-FOP-500x500.webp" },
  { id: 20, name: "Dabela chana", originalName: "Dabela Chana", price: 51, imageUrl: "Dabela-Chana_FOP-500x500.png" },
  { id: 21, name: "Chana dal", originalName: "Chana Dal", price: 51, imageUrl: "Chana-Dal_FOP-500x500.png" },
  { id: 22, name: "Sakkarpara", originalName: "Sakkarpara", price: 51, imageUrl: "Sakkarpara_FOP-500x500.webp" },
  { id: 23, name: "Masala noodles", originalName: "Masala Noodles", price: 42.5, imageUrl: "MasalaNoodles-FOP-500x500.webp" },
  { id: 24, name: "Masala wafers", originalName: "Masala Wafer", price: 52, imageUrl: "Masala-Wafer-FOP-500x500.webp" },
  { id: 25, name: "Salty(Kesari) wafers", originalName: "Salty (Kesari) Wafer", price: 52, imageUrl: "Salty_FOP-500x500.webp" },
  { id: 26, name: "Chilli wafers", originalName: "Chilli Wafer", price: 52, imageUrl: "Hot-Chilli_FOP-500x500.png" },
  { id: 27, name: "Creamy Onion", originalName: "Creamy Onion", price: 52, imageUrl: "Creamy_Onion_FOP_New_Image-500x500.webp" },
  { id: 28, name: "Salty Punch", originalName: "Salty Punch", price: 52, imageUrl: "SaltyPunch_FOP-500x500.webp" },
  { id: 29, name: "Tomato Wafer", originalName: "Tomato Wafer", price: 52, imageUrl: "Tomato_FOP-500x500.webp" },
  { id: 30, name: "Farali chevdo tikho", originalName: "Farali Chevdo (Tikha)", price: 51, imageUrl: "Farali-Chevdo_FOP-500x500.png" },
  { id: 31, name: "Farali chevdo mitho", originalName: "Farali Chevdo (Mitha)", price: 51, imageUrl: "Farali-Mitha-Chevda-FOP-500x500-1-500x500.webp" },
  { id: 32, name: "Vanela gathiya", originalName: "Vanela Gathiya", price: 51, imageUrl: "Vanela-Gathiya-1-500x500.png" },
  { id: 33, name: "Bhakharwadi", originalName: "Bhakharwadi", price: 51, imageUrl: "Bhakharvadi_FOP-500x500.png" },
  { id: 34, name: "Tikha gathiya", originalName: "Tikha Gathiya", price: 51, imageUrl: "TikhaGathiya_FOP-500x500.webp" },
  { id: 35, name: "Ratlami sev", originalName: "Ratlami Sev", price: 51, imageUrl: "Gokul-Ratlami-Sev-400g-FOP-500x500.webp" },
  { id: 36, name: "Sing bhujia", originalName: "Sing Bhujiya", price: 51, imageUrl: "SingBhujiya_FOP-500x500.webp" },
  { id: 37, name: "Nylon chivda", originalName: "Nylon Chivda", price: 51, imageUrl: "NylonSev-500x500.webp" },
  { id: 38, name: "Masala Peanuts", originalName: "Masala Peanuts", price: 51, imageUrl: "MasalaPeanuts_FOP-500x500.webp" },
  { id: 39, name: "Crunchy bites (Kaju)", originalName: "Crunchy Bites (Kaju)", price: 51, imageUrl: "Crunchy-Bites-FOP-500x500.webp" },
  { id: 40, name: "Lila toast", originalName: "Elaichi Toast", price: 102, imageUrl: "Elaichi-Toast-500x500.webp" },
  { id: 41, name: "Adad papad (₹10)", originalName: "Udad Papad", price: 8, imageUrl: "Papad_FOP-500x500.png" },
  { id: 42, name: "Chanadal (500g)", originalName: "Chanadal", price: 60, imageUrl: "Chana-Dal_FOP-500x500.png" },
  { id: 43, name: "Dabela chana (500g)", originalName: "Dabela Chana (500g)", price: 60, imageUrl: "Dabela-Chana_FOP-500x500.png" },
  { id: 44, name: "Bhavnagari gathiya (500g)", originalName: "Bhavnagri Gathiya (500g)", price: 60, imageUrl: "Bhavnagri-Gathiya-FOP-500x500.webp" },
  { id: 45, name: "Nylon gathiya (500g)", originalName: "Nylon Gathiya (500g)", price: 60, imageUrl: "NylonGathiya_FOP-500x500.webp" },
  { id: 46, name: "Vanela gathiya (500g)", originalName: "Vanela Gathiya (500g)", price: 60, imageUrl: "Vanela-Gathiya-1-500x500.png" },
  { id: 47, name: "Ratlami sev (500g)", originalName: "Ratlami Sev (500g)", price: 60, imageUrl: "Gokul-Ratlami-Sev-400g-FOP-500x500.webp" },
  { id: 48, name: "Sing bhujiya (500g)", originalName: "Sing Bhujiya (500g)", price: 75, imageUrl: "SingBhujiya_FOP-500x500.webp" },
  { id: 49, name: "Sakkarpara (500g)", originalName: "Sakkarpara (500g)", price: 60, imageUrl: "Sakkarpara_FOP-500x500.webp" },
  { id: 50, name: "Tikha mitha mix (500g)", originalName: "Tikha Mitha Mix (500g)", price: 65, imageUrl: "Tikha-Mitha-Mix-FOP-500x500.webp" }
];

export const balajiItemsList = [
  { name: "Wafers–simply salted", price: 51 },
  { name: "Wafers–masala masti", price: 51 },
  { name: "Wafers–tomato twist", price: 51 },
  { name: "Wafers–chaat chaska", price: 51 },
  { name: "Wafers–cream & onion", price: 51 },
  { name: "Peri peri wafers", price: 51 },
  { name: "Wafers–pizzy masala", price: 51 },
  { name: "Crunchex-simply salted", price: 51 },
  { name: "Crunchex-chilli tadka", price: 51 },
  { name: "Rumbles–pudina twist", price: 51 },
  { name: "Banana wafers–masala", price: 51 },
  { name: "Banana wafers–mari", price: 51 },
  { name: "Gippi noodles", price: 51 },
  { name: "Yumstix", price: 51 },
  { name: "Punjabi tadka", price: 51 },
  { name: "Flamin hot nachos", price: 51 },
  { name: "Cheese chilli nachos", price: 51 },
  { name: "Funne–spicy punch", price: 51 },
  { name: "Scoopitos", price: 51 },
  { name: "Poprings–yummy cheese", price: 51 },
  { name: "Poprings–masala", price: 51 },
  { name: "Wheelos–masala", price: 51 },
  { name: "Cp–flamin’ hot", price: 51 },
  { name: "Cp–chinese chaska", price: 51 },
  { name: "Cp–tangy tomato", price: 51 },
  { name: "Cp–masala masti", price: 51 },
  { name: "Khata mitha mix", price: 51 },
  { name: "Tikha mitha mix", price: 51 },
  { name: "Mitha farali chiwda", price: 51 },
  { name: "Farali chevdo", price: 51 },
  { name: "Chana jor garam", price: 51 },
  { name: "Bhel mix", price: 51 },
  { name: "Mung dal", price: 51 },
  { name: "Chana dal", price: 51 },
  { name: "Masala peas", price: 51 },
  { name: "Shing bhujia", price: 51 },
  { name: "Nimbu s.B.", price: 51 },
  { name: "Salted peanuts", price: 51 },
  { name: "Masala shing", price: 51 },
  { name: "Aloo sev", price: 51 },
  { name: "Classic sev", price: 51 },
  { name: "Gathiya", price: 51 },
  { name: "Ratlami sev", price: 51 },
  { name: "Sev murmura", price: 51 },
  { name: "Masala sev murmura", price: 51 },
];
