export const realItemsList = [
  { name: "Ratlami sev", price: 51 },
  { name: "Aaloo sev", price: 51 },
  { name: "Sing bhujiya", price: 51 },
  { name: "Moong dal", price: 54 },
  { name: "Soya stick", price: 51 },
  { name: "Soya chips", price: 51 },
  { name: "Tomato kurkure", price: 51 },
  { name: "Masala kurkure", price: 51 },
  { name: "Mora sevmamra", price: 51 },
  { name: "Tikha sevmamra", price: 51 },
  { name: "Bhel mamra", price: 51 },
  { name: "Farali tikho", price: 51 },
  { name: "Farali mitho", price: 54 },
  { name: "Tikhi papdi", price: 51 },
  { name: "Mori papdi", price: 51 },
  { name: "Pasta", price: 51 },
  { name: "Farali wafers", price: 54 },
  { name: "Mori wafers", price: 54 },
  { name: "Noodles", price: 50 },
  { name: "Polo ring", price: 50 },
  { name: "Jeera papad", price: 50 },
  { name: "Tikha papad", price: 50 },
  { name: "Tarzan", price: 50 },
  { name: "Mora bhoongala", price: 50 },
  { name: "Pani puri cup", price: 50 },
];

export const realItemsListGujarati = [
  { name: "રતલામી સેવ", price: 51 },
  { name: "આલૂ સેવ", price: 51 },
  { name: "સીંગ ભુજીયા", price: 51 },
  { name: "મૂંગ દાળ", price: 54 },
  { name: "સોયા સ્ટિક", price: 51 },
  { name: "સોયા ચિપ્સ", price: 51 },
  { name: "ટોમેટો કુરકુરે", price: 51 },
  { name: "વાડકા", price: 52 },
  { name: "પાણીપુરી વાડકા", price: 52 },
  { name: "મસાલા કુરકુરે", price: 51 },
  { name: "મોરા  સેવમમરા", price: 51 },
  { name: "તીખા સેવમમરા", price: 51 },
  { name: "ભેળ મમરા", price: 51 },
  { name: "ફરાળી તીખો", price: 51 },
  { name: "ફરાળી મીઠો", price: 54 },
  { name: "તીખી પાપડી", price: 51 },
  { name: "મોરી પાપડી", price: 51 },
  { name: "પાસ્તા", price: 51 },
  { name: "ફરાળી વેફર્સ", price: 54 },
  { name: "મોરી વેફર્સ", price: 54 },
  { name: "તીખી વેફર્સ", price: 54 },
  { name: "નૂડલ્સ", price: 50 },
  { name: "પોલો રીંગ", price: 50 },
  { name: "જીરા પાપડ", price: 50 },
  { name: "તીખા પાપડ", price: 50 },
  { name: "ટાર્ઝન", price: 50 },
  { name: "મોરા ભૂંગળા", price: 52 },
  { name: "પાણી પુરી કુરકુરે", price: 51 },
  { name: "ચાના દાળ", price: 51 },
  { name: "ચાના ચોર ગરમ", price: 51 },
  { name: "ગાંઠિયા", price: 51 },
  { name: "બીકાનેરી સેવ", price: 51 },
  { name: "મસાલા સીંગ", price: 51 },
  { name: "પંજાબી તડકા", price: 51 },
  { name: "ખટ્ટ મીઠ ચવાણું", price: 51 },
  { name: "નડિયાદી મિક્સ", price: 51 },
  { name: "ઇન્દોરી મિક્સ", price: 51 },
  { name: "પાપડ ચવાણું", price: 51 },
  { name: "પૌવા ચેવડા", price: 51 },
  { name: "મકાઈ ચેવડા", price: 51 },
  { name: "તીખા મીઠા મિક્સ", price: 51 },
  { name: "ઇનામ", price: 50 },
];

export const gokulItemsList = [
  { name: "Masala cup", price: 52 },
  { name: "Tomato cup", price: 52 },
  { name: "Plane", price: 52 },
  { name: "ABCD", price: 52 },
  { name: "Chowkadi", price: 52 },
  { name: "Plain ponga", price: 52 },
  { name: "Wheels", price: 52 },
  { name: "Pasta", price: 52 },
  { name: "Trayo", price: 52 },
  { name: "Raw Trayo", price: 52 },
  { name: "PopCorn", price: 52 },
  { name: "Corn V Garlic Chilli", price: 52 },
  { name: "Masala Corn V", price: 52 },
  { name: "Tomato Corn V", price: 52 },
  { name: "Bhavnagri gathiya", price: 51 },
  { name: "Nylon gathiya", price: 51 },
  { name: "Sev", price: 51 },
  { name: "Papdi", price: 51 },
  { name: "Tikha mitha mix", price: 51 },
  { name: "Dabela chana", price: 51 },
  { name: "Chana dal", price: 51 },
  { name: "Sakkarpara", price: 51 },
  { name: "Masala noodles", price: 42.5 },
  { name: "Masala kurkure", price: 51 },
  { name: "Tomato kurkure", price: 51 },
  { name: "Masala wafers", price: 52 },
  { name: "Salty(Kesari) wafers", price: 52 },
  { name: "Chilli wafers", price: 52 },
  { name: "Creamy Onion", price: 52 },
  { name: "Salty Punch", price: 52 },
  { name: "Tomato Wafer", price: 52 },
  { name: "Farali chevdo tikho", price: 51 },
  { name: "Farali chevdo mitho", price: 51 },
  { name: "Vanela gathiya", price: 51 },
  { name: "Bhakharwadi", price: 51 },
  { name: "Tikha gathiya", price: 51 },
  { name: "Ratlami sev", price: 51 },
  { name: "Sing bhujia", price: 51 },
  { name: "Nylon chivda", price: 51 },
  { name: "Masala Peanuts", price: 51 },
  { name: "Crunchy bites (Kaju)", price: 51 },
  { name: "Lila toast", price: 102},
  { name: "Adad papad (₹10)", price: 8 },
  { name: "Chanadal (500g)", price: 60 },
  { name: "Dabela chana (500g)", price: 60 },
  { name: "Bhavnagari gathiya (500g)", price: 60 },
  { name: "Nylon gathiya (500g)", price: 60 },
  { name: "Vanela gathiya (500g)", price: 60 },
  { name: "Ratlami sev (500g)", price: 60 },
  { name: "Sing bhujiya (500g)", price: 75 },
  { name: "Sakkarpara (500g)", price: 60 },
  { name: "Tikha mitha mix (500g)", price: 65 },
];

export const balajiItemsList = [
  { name: "Wafers–simply salted", price: 51 },
  { name: "Wafers–masala masti", price: 51 },
  { name: "Wafers–tomato twist", price: 51 },
  { name: "Wafers–chaat chaska", price: 51 },
  { name: "Wafers–cream & onion", price: 51 },
  { name: "Peri peri wafers", price: 51 },
  { name: "Wafers–pizzy masala", price: 51 },
  { name: "Crunchex-simply salted", price: 51 },
  { name: "Crunchex-chilli tadka", price: 51 },
  { name: "Rumbles–pudina twist", price: 51 },
  { name: "Banana wafers–masala", price: 51 },
  { name: "Banana wafers–mari", price: 51 },
  { name: "Gippi noodles", price: 51 },
  { name: "Yumstix", price: 51 },
  { name: "Punjabi tadka", price: 51 },
  { name: "Flamin hot nachos", price: 51 },
  { name: "Cheese chilli nachos", price: 51 },
  { name: "Funne–spicy punch", price: 51 },
  { name: "Scoopitos", price: 51 },
  { name: "Poprings–yummy cheese", price: 51 },
  { name: "Poprings–masala", price: 51 },
  { name: "Wheelos–masala", price: 51 },
  { name: "Cp–flamin’ hot", price: 51 },
  { name: "Cp–chinese chaska", price: 51 },
  { name: "Cp–tangy tomato", price: 51 },
  { name: "Cp–masala masti", price: 51 },
  { name: "Khata mitha mix", price: 51 },
  { name: "Tikha mitha mix", price: 51 },
  { name: "Mitha farali chiwda", price: 51 },
  { name: "Farali chevdo", price: 51 },
  { name: "Chana jor garam", price: 51 },
  { name: "Bhel mix", price: 51 },
  { name: "Mung dal", price: 51 },
  { name: "Chana dal", price: 51 },
  { name: "Masala peas", price: 51 },
  { name: "Shing bhujia", price: 51 },
  { name: "Nimbu s.B.", price: 51 },
  { name: "Salted peanuts", price: 51 },
  { name: "Masala shing", price: 51 },
  { name: "Aloo sev", price: 51 },
  { name: "Classic sev", price: 51 },
  { name: "Gathiya", price: 51 },
  { name: "Ratlami sev", price: 51 },
  { name: "Sev murmura", price: 51 },
  { name: "Masala sev murmura", price: 51 },
];
